name: Lint Checker
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Lint check
    permissions:
      contents: write
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer install

      - name: Run Rector
        run: |
          ./vendor/bin/rector --dry-run

      - name: Run Laravel Pint
        run: |
          ./vendor/bin/pint --test
