name: Automatic linter
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, gmp, intl, json, mysql, readline, sodium, bcmath, pcov
          tools: composer:v2

      - name: Install Laravel Pint and Rector
        run: |
          composer global require laravel/pint rector/rector

      - name: Run Rector
        run: |
          echo "$GITHUB_WORKSPACE"
          ls $GITHUB_WORKSPACE
          ls ${{ github.workspace }}
          composer global exec "rector process --config $GITHUB_WORKSPACE/rector.php"

      - name: Run Laravel Pint
        run: composer global exec "pint --config $GITHUB_WORKSPACE/pint.json"

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic linter"
