name: Linear Description Update
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.linear.app/graphql'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "test"}'
        data: '{"query":"mutation issueUpdate($input: IssueUpdateInput!, $issueUpdateId: String!) {\n  issueUpdate(input: $input, id: $issueUpdateId) {\n    success\n  }\n}","variables":{"input":{"description":"test"},"issueUpdateId":"PLA-2033"}}'
