name: Linear Description Update
on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://api.linear.app/graphql'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json", "Authorization": "test"}'
        data: '{"query": "mutation { issueUpdate(input: \"{ \"description\": \"test\" }\", id: \"PLA-2033\") { success } }" }'
