name: Linear Description Update
on:
  push:

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            mutation issueUpdate($input: IssueUpdateInput!, $issueUpdateId: String!) {
              issueUpdate(input: $input, id: $issueUpdateId) {
                success
              }
            }
          variables: |
            input: '{ "description": "test" }'
            issueUpdateId: "PLA-2033"
            headers: '{ "Authorization": "test" }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
